package powerworks.io;


public enum KeyControlOption implements ControlOption{
    UP, DOWN, LEFT, RIGHT, SPRINT, 
    DROP_ITEM, PICK_UP_ITEMS, 
    GIVE_CONVEYOR_BELT, GIVE_ORE_MINER, 
    EXIT, ROTATE_SELECTED_BLOCK, SHOW_UPDATE_TIMES, SHOW_RENDER_TIMES, 
    SLOT_1, SLOT_2, SLOT_3, SLOT_4, SLOT_5, SLOT_6, SLOT_7, SLOT_8,
    RENDER_HITBOX,
    OPEN_PLAYER_INVENTORY
}
